language: android
android:
  components:
    - android-22
    - build-tools-22.0.0
    - extra-android-support
    - extra-android-m2repository

script: ./gradlew build
notifications:
  hipchat:
    rooms:
      secure: WiQT1MnkaN41pXrDA/OFzpTU88K7UZZrV2ESGPD8Cz5KJOCJUeFZlmSlRZiwmVj5SBKP/7k2dVfmtoA/4exhKgRzei9UF63udwDBN63HCwb4CUGMWRbJYub99KB/QW5J52M4fsDd8w3p20I9L2ht9rZJMzqU+QPxcuNtkdEYZgA=