language: java
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a COMPONENTS=build-tools-19.0.1,android-19,sysimg-19,extra-android-m2repository
before_install:
  - export TERM=dumb
  - sudo apt-get install -qq libstdc++6:i386 lib32z1

  # install android build tools
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-1/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env

  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - chmod +x build.sh
  - chmod +x ci/wait_for_emulator.sh
  - ci/wait_for_emulator.sh
  - adb shell input keyevent 82

script: ./build.sh