"theme-smssync" :
  use : "theme"

"date_format": "%b %d, %Y"

production_url: 'http://smssync.ushahidi.com'

widgets :

  analytics :
    use : google
    # -- tracking code for google analytics --
    tracking_id : 'UA-12063676-22'

"CNAME" :
    use : "ignore"